### ISSUE TITLE
No module named 'deepSI.fit_systems.encoder_systems'

### ISSUE THREAD

**Issue by ngalioto** [GerbenBeintema/SS-encoder-WH-Silver#1]
When I try running the section "Fit/load state-space encoder model" from the "SS encoder Wiener-Hammerstein" Jupyter notebook, I get the error in the title. It seems that the deepSI code has changed since this repository was first uploaded. I tried changing the name in deepSI from 'encoders' back to 'encoder_systems', but there appear to be other incompatibilities as well.

**Comment by GerbenBeintema** [comment]
Thanks for the notice ngalioto, 

I have updated the repository to be compatible with the new version of deepSI (0.3.0). 

The original code used for the paper can always be found at [de3e48](https://github.com/GerbenBeintema/SS-encoder-WH-Silver/tree/de3e48e315e71a96581b22c5a71f7100313da7ff) and uses the 0.2 version of deepSI [d4d2111](https://github.com/GerbenBeintema/deepSI/tree/d4d21112325d10719fbb0a5561ef70c3bab87df8).
